name: 🐛 问题报告 Bug Report
description: 你发现了某个问题需要进行改进 
title: "请输入问题报告标题 Please enter the title of the bug report"
body:
  - type: checkboxes
    attributes:
      label: 该问题是否已经被报告过了？ Is there an existing issue for this?
      description: |
        请搜索以查看你遇到的问题是否已经被报告过。
      options:
        - label: |
            我已经搜索了 Issues，没有发现类似问题 
            I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: 描述问题 Describe the problem
      description: |
        请尽量清晰地描述你遇到的问题
    validations:
      required: true
  - type: textarea
    attributes:
      label: 期待的结果 Expected result
      description: |
        请尽量清晰地描述你所期待的结果。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 解决方案 Solution
      description: |
        请描述问题的最终解决方案
    validations:
      required: true
  - type: textarea
    attributes:
      label: 参考信息 Reference information
      description: |
        请提供任何附加信息，以帮助我们更好处理问题。
    validations:
      required: false
