name: 📑 开始新一天的规划和记录
description: 早上发表规划，中间进行记录，晚上进行总结评价
title: "请输入日记标题（时间-主要 事件/成果-情绪/状态）"
labels: "Diary"
body:
  - type: textarea
    attributes:
      label: 今天的目标是什么？What is the goal today?
      description: |
        请尽量清晰地描述今天的任务（任务要具体，有截止时间，难度要匹配你现在的能力
    validations:
      required: false
  - type: textarea
    attributes:
      label: 如何评价今天？ How would you evaluate today?
      value: |
        - 早上:
        
        - 下午: 
        
        - 晚上:
        
        - 总结:
        
      render: markdown
      description: |
        请客观评价今天的心情、状态、工作效率。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 今天有何收获？ Do you have any harvest today?
      description: |
        请描述你今天的成果和所得
    validations:
      required: false
  - type: textarea
    attributes:
      label: 你还有什么要说的？ Please share your other thoughts 
      value: |
        - 今天最开心的事情:
        
        - 今天最愤怒or悲伤的事情: 
        
      render: markdown
      description: |
        讲讲你今天的感悟和杂念
    validations:
      required: false
