name: ✨ 发布一篇日记 Request new features
description: 开始发布新的一天的记录 Come up with the features you expected
title: "请输入日记标题标题 Please enter the title of the feature request"
body:
  - type: textarea
    attributes:
      label: 今天的目标是什么？What is the goal today?
      description: |
        请尽量清晰地描述今天的任务（任务要具体，有截止时间，难度要匹配你现在的能力
    validations:
      required: true
  - type: textarea
    attributes:
      label: 如何评价今天？ How would you evaluate today?
      description: |
        请客观评价今天的心情、状态、工作效率。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 今天有何收获？ Do you have any harvest today?
      description: |
        请描述你今天的成果和所得
    validations:
      required: false
  - type: textarea
    attributes:
      label: 你还有什么要说的？ Please share your other thoughts 
      description: |
        讲讲你今天的感悟和杂念
    validations:
      required: false
