name: ✨ 发布一篇日记 
description: 开始发布新的一天的记录 
title: "请输入日记标题标题"
body:
  - type: textarea
    attributes:
      label: 今天的目标是什么？
      description: |
        请尽量清晰地描述今天的任务（任务要具体，有截止时间，难度要匹配你现在的能力
    validations:
      required: true
  - type: textarea
    attributes:
      label: 如何评价今天？ 
      description: |
        请客观评价今天的心情、状态、工作效率。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 今天有何收获？ 
      description: |
        请描述你今天的成果和所得
    validations:
      required: false
  - type: textarea
    attributes:
      label: 你还有什么想要说的？
      description: |
        讲讲你今天的感悟和杂念
       
    validations:
      required: false
