name: ✨ 发起提议 
description: 提出想要实现的目标或者想法 
title: "请输入提议标题"
body:
  - type: textarea
    attributes:
      label: 请描述你的提议
      description: |
        请尽量清晰地描述该特性的应用场景。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 你发起提议的动机是什么？What was your motivation for making the request?
      description: |
        请描述你能想到的提出提议的动机。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 这个提议困难吗？难点在哪里？can you complete this task？
      description: |
        请分析这个提议的可行性
    validations:
      required: true
  - type: textarea
    attributes:
      label: 描述该提议的实现方案 Describe the implementation steps
      description: |
        请记录为了实现这个提议需要经历的步骤
    validations:
      required: false
  - type: textarea
    attributes:
      label: 其他信息 Other information
      description: |
        请提供任何附加信息，以帮助我们更好实现该提议
    validations:
      required: false
