name: ✨ 发起提议 Request new features
description: 欢迎提出你所期待的新特性 Come up with the features you expected
title: "请输入提议标题 Please enter the title of the feature request"
body:
  - type: textarea
    attributes:
      label: 请描述你的提议 Please describe your proposal
      description: |
        请尽量清晰地描述该特性的应用场景。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 你发起提议的动机是什么？What was your motivation for making the request?
      description: |
        请描述你能想到的提出提议的动机。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 描述候选的解决方案 Describe the candidate solution
      description: |
        请描述你能想到的候选解决方案。
    validations:
      required: false
  - type: textarea
    attributes:
      label: 其他信息 Other information
      description: |
        请提供任何附加信息，以帮助我们更好地理解该特性和解决方案。
    validations:
      required: false
