name: ✨ 发起提议 Request new features
description: 欢迎提出你所期待的新特性 Come up with the features you expected
title: "请输入提议标题 Please enter the title of the feature request"
body:
  - type: textarea
    attributes:
      label: 请描述你的提议 Please describe your proposal
      description: |
        你想实现什么目标？
    validations:
      required: false
  - type: textarea
    attributes:
      label: 你发起提议的动机是什么？What was your motivation for making the proposal?
      description: |
        请尽量清晰地描述该提议的动机。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 你觉你可以完成这个提议吗？ Describe the optimal solution
      description: |
        请分析该提议的可行性
    validations:
      required: true
  - type: textarea
    attributes:
      label: 描述提议的实现步骤 Describe the implementation steps
      description: |
        请描述你能想到的实现步骤。
      required: false
  - type: textarea
    attributes:
      label: 参考信息 Reference information
      description: |
        请提供任何参考信息，以帮助实现该提议
    validations:
      required: false
