name: ✨ 发起提议 Request new features
description: 欢迎提出你所期待的新特性 Come up with the features you expected
title: "请输入提议标题 Please enter the title of the feature request"
body:
  - type: textarea
    attributes:
      label: 请描述你的提议 Please describe your proposal
      description: |
        请尽量清晰地描述该特性的应用场景。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 你发起提议的动机是什么？What was your motivation for making the request?
      description: |
        请描述你能想到的提出提议的动机。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 你觉得你可以完成这个提议吗？can you complete this task？
      description: |
        请分析这个提议的可行性
    validations:
      required: true
  - type: textarea
    attributes:
      label: 描述该提议的实现方案 Describe the implementation steps
      description: |
        请记录为了实现这个提议需要经历的步骤
    validations:
      required: false
  - type: textarea
    attributes:
      label: 其他信息 Other information
      description: |
        请提供任何附加信息，以帮助我们更好实现该提议
    validations:
      required: false
